name: row_item
description: Display compat information by using two widgets separated inside a row widget.
version: 2.0.0
homepage: https://github.com/jesusrp98/row_item

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
