name: row_item
description: Allows to display compat information inside a row.
version: 1.0.0
homepage: https://github.com/jesusrp98/row_item

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
